version: "3.4"

services:
  caddy:
    image: swarm_caddy-build:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: "0.1"
          memory: 200M
    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Caddyfile:/config/Caddyfile
    environment:
      - CADDY_INGRESS_NETWORKS=public
      - CADDY_DOCKER_CADDYFILE_PATH=/config/Caddyfile
    #command: "sh -c 'while true; do sleep 3; done'"
    networks: 
      - public

networks:
  public:
    external: true